// <auto-generated />
namespace MVIOperationsSystem.Migrations.LocalStorage
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addxamlware : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addxamlware));
        
        string IMigrationMetadata.Id
        {
            get { return "202008040945233_addxamlware"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
